### ISSUE TITLE
Youtube Campaign has been removed

### ISSUE THREAD

**Issue by QAtests2020** [CryptoPolicePlatform/cryptopolice-platform-cms#11]
There is no Youtube Campaign. Link in this item leads to the 'Bounty Campaigns' page 

**Actual result:** Youtube Campaign is now 'Camplaign' in 'Registered Bounty Campaigns' . The link is not correct. There is no Youtube in 'Bounty Campaigns' list
![image](https://user-images.githubusercontent.com/37227273/37521338-6b33fe28-2931-11e8-9fa0-d8640867375c.png)

**Comment by vladimirs-cryptopolice** [comment]
The Youtube Campaign has been deleted, registrations will be deleted soon.
