### ISSUE TITLE
.bmp images are not availible for avatar profile

### ISSUE THREAD

**Issue by QAtests2020** [CryptoPolicePlatform/cryptopolice-platform-cms#2]
Users can't upload .bmp images for avatar in profile

**Conditions:**
- .bmp images

**Steps:**
1. Download any .bmp image into your local storage
2. Log in to system
3. Go to profile settings
4. Click on "Change Avatar" button
5. Try to find the file from Step 1

**Actual result:** The .bmp images are not displayed in folder on local storage
_Expected result:_ Users can use .bmp images for avatar

**Comment by vladimirs-cryptopolice** [comment]
The user is able to upload (*.jpg, *.jpeg, *.png). 
*.bmp is invalid format for plugin.
